version: '3.9'

services:
  api:
    container_name: api
    build:
      context: .
    command: php -S 0.0.0.0:8080 public/index.php
    volumes:
      - ./src:/usr/src/api
      - api-data:/usr/src/api/vendor
    depends_on:
      - postgres
    working_dir: /usr/src/api
    ports:
      - 8080:8080

  postgres:
    container_name: postgres
    image: postgres:14.2-alpine
    environment:
      - POSTGRES_PASSWORD=password
      - POSTGRES_USER=api
      - POSTGRES_DB=api
    volumes:
      - postgres-data:/var/lib/postgresql/data
    ports:
      - 5432:5432

volumes:
  api-data:
  postgres-data:
