---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: github-api
  namespace: github-api
  labels:
    app: github-api
spec:
  replicas: 2
  selector:
    matchLabels:
      app: github-api
  template:
    metadata:
      labels:
        app: github-api
    spec:
      containers:
      - name: github-api
        image: gerardorochin/github-api:latest
        imagePullPolicy: IfNotPresent
        envFrom:
          - configMapRef:
              name: github-api-configmap
        resources:
          requests:
            memory: "16Mi"
            cpu: "100m"
          limits:
            memory: "32Mi"
            cpu: "200m"
        ports:
        - containerPort: 8080