---
apiVersion: v1
kind: ConfigMap
metadata:
  name: github-api-configmap
  namespace: github-api
data:
    APP_NAME: "Api"
    APP_ENV: "production"
    APP_KEY: "ouyo9PheiMaivemi"
    APP_DEBUG: "true"
    APP_URL: "http://localhost:8080"
    APP_TIMEZONE: "America/Mexico_City"
    DB_CONNECTION: "pgsql"
    DB_HOST: "postgres.github-api.svc.cluster.local"
    DB_PORT: "5432"
    DB_DATABASE: "api"
    DB_USERNAME: "api"
    DB_PASSWORD: "password"

    CACHE_DRIVER: "file"
    QUEUE_CONNECTION: "sync"

    GITHUB_TOKEN: ""
